#!/bin/sh

PROFILE="$HOME/.profile"
USER_RUNTIME_DIR="/var/run/user/$(id -u)"

# Ensure the file exists
if [ ! -f "$PROFILE" ]; then
    touch "$PROFILE"
fi



echo "==> Ensuring XDG runtime directory exists: $USER_RUNTIME_DIR"

if [ ! -d "$USER_RUNTIME_DIR" ]; then
    echo "Directory does not exist. Creating..."
    sudo mkdir -p "$USER_RUNTIME_DIR"
else
    echo "Directory already exists."
fi

echo "Fixing ownership and permissions..."
sudo chown -R "${USER}":wheel "$USER_RUNTIME_DIR"
sudo chmod 700 "$USER_RUNTIME_DIR"

add_line() {
    KEY="$1"
    LINE="$2"

    if grep -q "^$KEY=" "$PROFILE"; then
        echo "$KEY already exists in .profile"
    elif grep -q "$LINE" "$PROFILE"; then
        echo "$KEY already present in .profile"
    else
        echo "Adding $KEY to .profile"
        echo "$LINE" >> "$PROFILE"
    fi
}

add_line "export XDG_CONFIG_HOME"  'export XDG_CONFIG_HOME="$HOME/.config"'
add_line "export XDG_CACHE_HOME"   'export XDG_CACHE_HOME="$HOME/.cache"'
add_line "export XDG_DATA_HOME"    'export XDG_DATA_HOME="$HOME/.local/share"'
add_line "export XDG_RUNTIME_DIR"  "export XDG_RUNTIME_DIR=\"/var/run/user/$(id -u)\""

if ! id -G "$USER" | grep -qw "$(id -g video)"; then
    sudo pw groupmod video -m "$USER"
fi

sudo sysrc seatd_enable="YES"
sudo service seatd start